#!/bin/sh

function createpy(){
  touch $1
  echo "#!/usr/bin/env python" > $1
  echo "# -*- coding: utf-8 -*" >> $1
  echo "# Filename : $1" >> $1
  vim $1
}

if [ -z $1 ]
then
  echo "Usage: ./_pycreate [file name]"
  exit 0
fi

if [ -f $1 ]
then
  echo $1" is exist, OVERWRITE it? (y/n) :"
  read ANS
  case $ANS in 
    y|Y|yes|Yes|YES)
      createpy $1
      ;;
    n|N|no|No|NO)
      exit 0
      ;;
  esac

else
  createpy $1
fi
